%OPTOSPLIT
%
%   Given a calibration file, splits a 3-dimensional timelapse of images
%   (X,Y,t) into a 4-dimensional timelapse of images (X,Y,t,c).

function [ imout ] = optosplit( varargin )

% check inputs

numvarargs = length( varargin );

if numvarargs == 0
    % open alignement file as generated by java script
    [ name, path ] = uigetfile( '.csv',...
        'Please select the alignment file', '/Volumes/WAC26' );
    alignFile = strcat( path, name );
    [ name, path ] = uigetfile( '.tif',...
        'Please select the image file', '/Volumes/WAC26' );
    imFile = strcat( path, name );
    [ name, path ] = uiputfile( '.tif',...
        'Please select output file', '/Volumes/WAC26' );
    outFile = strcat( path, name );
elseif numvarargs == 2
    alignFile = varargin{ 1 };
    imFile = varargin{ 2 };
else
    error( 'optosplit takes two input arguments - file locations for the alignment file and the image file' );
end

alignment = csvread( alignFile );

r1 = alignment(1,:)
r2 = alignment(2,:)

timeSteps = length( imfinfo( imFile ) );

t = 1;

im = imread( imFile, t );
ic = imcrop(im, r1);
imshow( ic, [min(ic(:)), max(ic(:))] );


end

function [ imout ] = imcrop( im, r )

imout = im(r(2):r(2)+r(3), r(1):r(1)+r(4));

end
    
            
            